-- INSERT INTO bib_users (userId, username, email, password, enabled)
--   values
--   ('1000', 'admin', 'admin@email.com', 'pass', 1),
--   ('1001', 'user', 'user@email.com', 'pass', 1);
-- --   ('Markus Meier', 'markus.meier@email.com', 'UnVuG9HHgffUDAlk8qfOu', 1),
-- --   ('Klaus Fichte', 'klaus.fichte@email.com', 'UnVuG9HHgffUDAlk8qfOu', 1),
-- --   ('Denise Richards', 'denise.richards@email.com', 'UnVuG9HHgffUDAlk8qfOu', 1);
--
-- INSERT INTO authorities (userId, authority)
--   values
--   ('1000', 'ROLE_ADMIN'),
--   ('1001', 'ROLE_USER');