-- MySQL Script generated by MySQL Workbench
-- Sat Jun 13 15:07:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bibdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bibdb` ;

-- -----------------------------------------------------
-- Schema bibdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bibdb` DEFAULT CHARACTER SET utf8 ;
USE `bibdb` ;

-- -----------------------------------------------------
-- Table `bibdb`.`members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibdb`.`members` ;

CREATE TABLE IF NOT EXISTS `bibdb`.`members` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(250) NULL DEFAULT NULL,
  `name` VARCHAR(150) NULL DEFAULT NULL,
  `surname` VARCHAR(150) NULL,
  `email` VARCHAR(250) NULL DEFAULT NULL,
  `enabled` INT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bibdb`.`authorities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibdb`.`authorities` ;

CREATE TABLE IF NOT EXISTS `bibdb`.`authorities` (
  `username_ref` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NULL DEFAULT NULL,
  `members_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username_ref`, `members_username`),
  INDEX `fk_authorities_members_idx` (`members_username` ASC),
  CONSTRAINT `fk_authorities_members`
    FOREIGN KEY (`members_username`)
    REFERENCES `bibdb`.`members` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibdb`.`autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibdb`.`autor` ;

CREATE TABLE IF NOT EXISTS `bibdb`.`autor` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibdb`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibdb`.`book` ;

CREATE TABLE IF NOT EXISTS `bibdb`.`book` (
  `id` INT NOT NULL,
  `autor_id` INT NULL,
  `name` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_book_autor1_idx` (`autor_id` ASC),
  CONSTRAINT `fk_book_autor1`
    FOREIGN KEY (`autor_id`)
    REFERENCES `bibdb`.`autor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
